{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "1287c253_fdc8629e",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 7
      },
      "lineNbr": 0,
      "author": {
        "id": 1003571
      },
      "writtenOn": "2021-12-04T00:36:57Z",
      "side": 1,
      "message": "I\u0027m not sure what\u0027s wrong with this, but pynfs 4.1 fails miserably.\n\nI didn\u0027t change configuration.",
      "revId": "09f39cdab0bd66e88b0eb9a1157c0254021ff58b",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    }
  ]
}