{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "5605995a_85eb8876",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1003571
      },
      "writtenOn": "2021-04-30T22:58:44Z",
      "side": 1,
      "message": "OK, I\u0027m not sure about this one. I\u0027m all of a sudden getting flooded with errors when running pynfs4.1\n\nI\u0027m not sure how this is supposed to work. I\u0027d like more discussion before merging.",
      "revId": "62a66d96fdd91b83516db3991fe4fecf23938f3d",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    }
  ]
}