{
  "comments": [
    {
      "key": {
        "uuid": "6f074994_da2b655a",
        "filename": "src/FSAL/FSAL_CEPH/handle.c",
        "patchSetId": 3
      },
      "lineNbr": 1287,
      "author": {
        "id": 1008909
      },
      "writtenOn": "2019-05-16T11:28:52Z",
      "side": 1,
      "message": "In v4.1+, I think this is supposed to result in NFS4ERR_WRONG_TYPE if it\u0027s not a symlink. Maybe we need a new ERR_FSAL_WRONGTYPE or something that will translate to that?",
      "revId": "872c9990e2379a11f664d4fe135ea15798440186",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "48c9df96_32676f24",
        "filename": "src/FSAL/FSAL_CEPH/handle.c",
        "patchSetId": 3
      },
      "lineNbr": 1287,
      "author": {
        "id": 1003571
      },
      "writtenOn": "2019-05-16T14:00:22Z",
      "side": 1,
      "message": "Hmm, we don\u0027t use that error at all...\n\nI guess pynfs doesn\u0027t require it...\n\nI will look into when we should use that error as opposed to the others and fix it up.",
      "parentUuid": "6f074994_da2b655a",
      "revId": "872c9990e2379a11f664d4fe135ea15798440186",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": true
    }
  ]
}