{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "4e76a1b5_0607e966",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1020789
      },
      "writtenOn": "2022-12-21T21:22:40Z",
      "side": 1,
      "message": "(I am new to Gerrit. Hope that I did not screw things up...)",
      "revId": "92b992df8f26aa038eb057686d418b0613908533",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "9c631f90_4d7dc548",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1020789
      },
      "writtenOn": "2022-12-22T17:58:00Z",
      "side": 1,
      "message": "The CI issue seems unrelated\n\n\"\"\"\nAn unexpected error occured: \u003curlopen error [Errno 111] Connection refused\u003e\nWaiting 300 seconds before retrying #1...\nAn unexpected error occured: \u003curlopen error [Errno 111] Connection refused\u003e\nWaiting 300 seconds before retrying #2...\n\"\"\"",
      "revId": "92b992df8f26aa038eb057686d418b0613908533",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    }
  ]
}