{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "1b4d8600_5f2aab15",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 1003571
      },
      "writtenOn": "2021-03-02T20:54:13Z",
      "side": 1,
      "message": "I have run pynfs4.0, pynfs4.1, and cthon04 (via NFS v4.1) on this and all passed.",
      "revId": "bfe11f441d87a938736ded44913ffac935ecc4cf",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735"
    }
  ]
}